CREATE TABLE IF NOT EXISTS user_addresses (
  id SERIAL PRIMARY KEY,
  userId UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  phone_number VARCHAR(20) NOT NULL,
  alternate_phone VARCHAR(20),
  address_line1 VARCHAR(255) NOT NULL,
  address_line2 VARCHAR(255),
  landmark VARCHAR(255),
  region_code VARCHAR(20) NOT NULL,
  province_code VARCHAR(20) NOT NULL,
  city_municipality_code VARCHAR(20) NOT NULL,
  barangay_code VARCHAR(20) NOT NULL,
  region_name VARCHAR(255) NOT NULL,
  province_name VARCHAR(255) NOT NULL,
  city_municipality_name VARCHAR(255) NOT NULL,
  barangay_name VARCHAR(255) NOT NULL,
  postal_code VARCHAR(4) NOT NULL,
  address_type VARCHAR(20) DEFAULT 'home',
  is_default BOOLEAN DEFAULT FALSE,
  delivery_instructions TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
